### ISSUE TITLE
Readiness probe failed: Get http://10.244.0.58:8761/: dial tcp 10.244.0.58:8761: connect: connection refused

### ISSUE THREAD

**Issue by kevinzouwf** [BitInit/eureka-on-kubernetes#1]
报这个错了？

**Comment by BitInit** [comment]
readiness开始检查时间是30s，可能30s的时候eureka还没有启动起来，多等段时间，eureka cluster稳定后再看看

**Comment by kevinzouwf** [comment]
我把这个时间调到600秒后，有其他报错。
2019-06-04 11:34:32.047  WARN 1 --- [nfoReplicator-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: java.net.UnknownHostException: eureka-0.eureka: System error
2019-06-04 11:34:32.059 ERROR 1 --- [nfoReplicator-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error

com.sun.jersey.api.client.ClientHandlerException: java.net.UnknownHostException: eureka-2.eureka: System error

**Comment by BitInit** [comment]
eureka cluster是使用的是stateful set方式，k8s是以顺序启动3个eureka的，当启动了eureka-0，但是还没有启动eureka-1和eureka-2时，eureka-0向eureka-1和eureka-2进行服务注册就会出现上面的报错。

没必要将时间调到600s，按readme文档启动eureka集群，过个几分钟后通过eureka ui可查看服务情况，开始报的这些错误属于正常现象。

**Comment by kevinzouwf** [comment]
我安装你的文档启动集群，eureka-0一直是runing状态
[root@master1 eureka-on-kubernetes]# kubectl get pods 
NAME                           READY   STATUS    RESTARTS   AGE
eureka-0                       0/1     Running   6          16m

[root@master1 eureka-on-kubernetes]# kubectl describe pod  eureka-0
  Normal   Scheduled  14m                   default-scheduler  Successfully assigned default/eureka-0 to master1
  Warning  Unhealthy  9m50s (x6 over 12m)   kubelet, master1   Liveness probe failed: Get http://10.244.0.64:8761/: dial tcp 10.244.0.64:8761: connect: connection refused
  Normal   Pulling    9m49s (x3 over 14m)   kubelet, master1   pulling image "bitinit/eureka"
  Normal   Killing    9m49s (x2 over 12m)   kubelet, master1   Killing container with id docker://eureka:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Pulled     9m45s (x3 over 14m)   kubelet, master1   Successfully pulled image "bitinit/eureka"
  Normal   Created    9m45s (x3 over 14m)   kubelet, master1   Created container
  Normal   Started    9m45s (x3 over 14m)   kubelet, master1   Started container
  Warning  Unhealthy  4m51s (x12 over 12m)  kubelet, master1   Readiness probe failed: Get http://10.244.0.64:8761/: dial tcp 10.244.0.64:8761: connect: connection refused

**Comment by BitInit** [comment]
我刚试了下，按照文档跑我这里没有问题。你检查一下kubernetes这块是否正常。

**Comment by kevinzouwf** [comment]
已经解决这个问题了，我们这边的eureka包加了认证，需要用户密码。由http改成tcp就可以了，感谢你的帮助！
        livenessProbe:
          tcpSocket:
            port:  8761
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port:  8761
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
